# Generated by Django 5.1.7 on 2025-03-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageserver', '0003_usergroup_alter_message_group_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(max_length=255),
        ),
    ]
