# Generated by Django 5.1.7 on 2025-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageserver', '0004_alter_usergroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='password',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
