# Generated by Django 5.1.6 on 2025-03-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0004_otp'),
        ('groupstudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creategroup',
            name='auth_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creategroup', to='accountsapp.account'),
            preserve_default=False,
        ),
    ]
