# Generated by Django 5.1.7 on 2025-03-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudy', '0004_rename_group_groupmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
