# Generated by Django 5.1.7 on 2025-04-09 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudy', '0007_groupstudy_delete_creategroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudy',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
