# Generated by Django 5.1.7 on 2025-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
